FROM uqr/base:latest

# Add DV workspace and build
RUN mkdir -p /ws/dv_ws
WORKDIR /ws/dv_ws

COPY src src
COPY .catkin_tools .catkin_tools
RUN catkin config --extend /opt/ros/noetic
RUN catkin build
RUN touch /root/.bashrc
ARG entrypointReplacement="Xvfb :1 -screen 0 1600x1200x16  & \nexport DISPLAY=:1.0 \nsource "


# Append to Entry Point
ARG WSPATH="/ws/dv_ws"
RUN sed --in-place --expression \
  '$isource /ws/dv_ws/devel/setup.bash\n\n# Setup Screen Forwarding \nXvfb :1 -screen 0 1600x1200x16  & \nexport DISPLAY=:1.0'\
  /ros_entrypoint.sh